export const NOZZLE_NAMES = ['nozzle', 'nozzle1', 'Nozzle', 'Nozzle1', 'Nuzzle', 'nuzzle', 'Nuzzle1', 'nuzzle1'];

export function findNozzleNode(model) {
    let found = null;
    model.traverse((child) => {
        // Only looking for Object3D nodes with matching name
        if (!found && child.isObject3D && NOZZLE_NAMES.includes(child.name)) {
            found = child;
        }
    });
    return found;
}

export function findGripNode(model, gripName = 'Grip') {
    let found = null;
    model.traverse((child) => {
        if (!found && child.isObject3D && child.name === gripName) {
            found = child;
        }
    });
    return found;
}

export const GUN_REGISTRY = {
    'g88_workhorse': {
        id: 'g88_workhorse',
        name: 'G-88 Workhorse',
        slot: 'primary',
        modelPath: 'G-88 Workhorse.glb',
        type: 'assault rifle',
        mechanics: {
            fireMode: 'auto',
            damage: 25,
            headshotMult: 1.5,
            pellets: null,
            fireRate: 600,
            magSize: 30,
            reserveAmmo: 120,
            reloadTime: 2.2,
            reloadType: 'magazine',
            bulletSpeed: Infinity,
            projectile: false,
            gravity: null,
            splashDamage: null,
            splashRadius: null,
            range: 30,
            rangeFalloff: 0.7,
            recoilPattern: [[0, 0.05], [0.02, 0.08], [-0.03, 0.12], [0.04, 0.15], [-0.05, 0.18], [0.02, 0.12]],
            recoilRecovery: 0.8,
            spread: 0.04,
            adsSpread: 0.01,
            hipfireSpread: null,
            moveSpreadMult: 1.5,
            scopeFOV: null,
            breathSway: null,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: 'Grip_2',
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: 'socket_Lefthand',
        },
        visualFX: {
            muzzleColor: '#FFD700',
            muzzleScale: 2.5,
            tracerColor: '#FFD700',
            tracerWidth: 0.1,
            impactColor: '#FFD700',
            impactScale: 1.5,
            shellEject: true,
        }
    },
    'kilometer': {
        id: 'kilometer',
        name: 'Kilometer',
        slot: 'primary',
        modelPath: 'Kilometer.glb',
        type: 'automatic shotgun',
        mechanics: {
            fireMode: 'auto',
            damage: 12,
            headshotMult: 1.2,
            pellets: 8,
            fireRate: 180,
            magSize: 12,
            reserveAmmo: 48,
            reloadTime: 0.6,
            reloadType: 'shell_by_shell',
            bulletSpeed: Infinity,
            projectile: false,
            gravity: null,
            splashDamage: null,
            splashRadius: null,
            range: 10,
            rangeFalloff: 0.3,
            recoilPattern: [[0, 0.25], [0.05, 0.3], [-0.05, 0.35], [0, 0.25], [0.1, 0.4]],
            recoilRecovery: 1.0,
            spread: 0.12,
            adsSpread: 0.08,
            hipfireSpread: null,
            moveSpreadMult: 1.3,
            scopeFOV: null,
            breathSway: null,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: 'Grip_2',
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: 'socket_Lefthand',
        },
        visualFX: {
            muzzleColor: '#FF6600',
            muzzleScale: 3.5,
            tracerColor: '#FF6600',
            tracerWidth: 0.15,
            impactColor: '#FF6600',
            impactScale: 2.0,
            shellEject: true,
        }
    },
    'shotta': {
        id: 'shotta',
        name: 'Shotta',
        slot: 'primary',
        modelPath: 'shotta.glb',
        type: 'pump shotgun',
        mechanics: {
            fireMode: 'pump',
            pumpTime: 0.92,
            damage: 18,
            headshotMult: 1.2,
            pellets: 10,
            fireRate: 65,
            magSize: 6,
            reserveAmmo: 30,
            reloadTime: 0.8,
            reloadType: 'shell_by_shell',
            bulletSpeed: Infinity,
            projectile: false,
            gravity: null,
            splashDamage: null,
            splashRadius: null,
            range: 8,
            rangeFalloff: 0.2,
            recoilPattern: [[0, 0.4], [0.05, 0.45], [-0.05, 0.45], [0, 0.5], [0.02, 0.45]],
            recoilRecovery: 1.2,
            spread: 0.15,
            adsSpread: 0.10,
            hipfireSpread: null,
            moveSpreadMult: 1.2,
            scopeFOV: null,
            breathSway: null,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: 'Grip_2',
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: 'socket_Lefthand',
        },
        visualFX: {
            muzzleColor: '#FF3300',
            muzzleScale: 4.0,
            tracerColor: '#FF3300',
            tracerWidth: 0.2,
            impactColor: '#FF3300',
            impactScale: 2.5,
            shellEject: true,
        }
    },
    'sniper': {
        id: 'sniper',
        name: 'Sniper',
        slot: 'primary',
        modelPath: 'sniper.glb',
        type: 'bolt-action sniper',
        mechanics: {
            fireMode: 'bolt',
            boltTime: 1.1,
            damage: 85,
            headshotMult: 2.5,
            pellets: null,
            fireRate: 54, // ~1.1s bolt cycle
            magSize: 5,
            reserveAmmo: 25,
            reloadTime: 3.5,
            reloadType: 'magazine',
            bulletSpeed: Infinity,
            projectile: false,
            gravity: null,
            splashDamage: null,
            splashRadius: null,
            range: Infinity,
            rangeFalloff: null,
            recoilPattern: [[0, 0.8], [0.05, 0.9], [-0.05, 0.85], [0, 0.95], [0.02, 0.85]],
            recoilRecovery: 0.5,
            spread: 0.18,
            adsSpread: 0,
            hipfireSpread: 0.18,
            moveSpreadMult: 2.5,
            scopeFOV: 22,
            breathSway: 0.05,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: 'Grip_2',
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: 'socket_Lefthand',
        },
        visualFX: {
            muzzleColor: '#00FFFF',
            muzzleScale: 3.0,
            tracerColor: '#00FFFF',
            tracerWidth: 0.15,
            impactColor: '#00FFFF',
            impactScale: 2.0,
            shellEject: true,
        }
    },
    'the_mainline': {
        id: 'the_mainline',
        name: 'The Mainline',
        slot: 'primary',
        modelPath: 'The Mainline.glb',
        type: 'tactical assault rifle',
        mechanics: {
            fireMode: 'auto',
            damage: 22,
            headshotMult: 1.6,
            pellets: null,
            fireRate: 750,
            magSize: 30,
            reserveAmmo: 120,
            reloadTime: 2.0,
            reloadType: 'magazine',
            bulletSpeed: Infinity,
            projectile: false,
            gravity: null,
            splashDamage: null,
            splashRadius: null,
            range: 35,
            rangeFalloff: 0.75,
            recoilPattern: [[0, 0.04], [0.01, 0.06], [-0.02, 0.08], [0.03, 0.11], [-0.04, 0.14], [0.01, 0.09]],
            recoilRecovery: 0.9,
            spread: 0.03,
            adsSpread: 0.005,
            hipfireSpread: null,
            moveSpreadMult: 1.4,
            scopeFOV: null,
            breathSway: null,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: 'Grip_2',
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: 'socket_Lefthand',
        },
        visualFX: {
            muzzleColor: '#FF00FF',
            muzzleScale: 2.2,
            tracerColor: '#FF00FF',
            tracerWidth: 0.08,
            impactColor: '#FF00FF',
            impactScale: 1.3,
            shellEject: true,
        }
    },
    'v3_interval': {
        id: 'v3_interval',
        name: 'V-3 Interval',
        slot: 'primary',
        modelPath: 'V-3 Interval.glb',
        type: 'burst assault rifle',
        mechanics: {
            fireMode: 'burst',
            burstCount: 3,
            burstDelay: 0.08,
            burstCooldown: 0.35,
            damage: 26,
            headshotMult: 1.5,
            pellets: null,
            fireRate: 750,
            magSize: 30,
            reserveAmmo: 120,
            reloadTime: 2.3,
            reloadType: 'magazine',
            bulletSpeed: Infinity,
            projectile: false,
            gravity: null,
            splashDamage: null,
            splashRadius: null,
            range: 40,
            rangeFalloff: 0.8,
            recoilPattern: [[0, 0.03], [0.01, 0.06], [-0.01, 0.09], [0, 0.04], [0.01, 0.07], [-0.01, 0.1]],
            recoilRecovery: 1.1,
            spread: 0.035,
            adsSpread: 0.008,
            hipfireSpread: null,
            moveSpreadMult: 1.4,
            scopeFOV: null,
            breathSway: null,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: 'Grip_2',
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: 'socket_Lefthand',
        },
        visualFX: {
            muzzleColor: '#00FF88',
            muzzleScale: 2.3,
            tracerColor: '#00FF88',
            tracerWidth: 0.09,
            impactColor: '#00FF88',
            impactScale: 1.4,
            shellEject: true,
        }
    },
    'tungsten': {
        id: 'tungsten',
        name: 'Tungsten',
        slot: 'secondary',
        modelPath: 'Tungsten.glb',
        type: 'heavy pistol',
        mechanics: {
            fireMode: 'semi',
            damage: 45,
            headshotMult: 1.8,
            pellets: null,
            fireRate: 200,
            magSize: 8,
            reserveAmmo: 40,
            reloadTime: 1.8,
            reloadType: 'magazine',
            bulletSpeed: Infinity,
            projectile: false,
            gravity: null,
            splashDamage: null,
            splashRadius: null,
            range: 20,
            rangeFalloff: 0.6,
            recoilPattern: [[0, 0.15], [0.02, 0.18], [-0.03, 0.2], [0.04, 0.22], [-0.02, 0.18]],
            recoilRecovery: 1.5,
            spread: 0.06,
            adsSpread: 0.02,
            hipfireSpread: null,
            moveSpreadMult: 1.2,
            scopeFOV: null,
            breathSway: null,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: null,
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: null,
        },
        visualFX: {
            muzzleColor: '#FFAA00',
            muzzleScale: 1.8,
            tracerColor: '#FFAA00',
            tracerWidth: 0.08,
            impactColor: '#FFAA00',
            impactScale: 1.5,
            shellEject: true,
        }
    },
    'direct_blaser': {
        id: 'direct_blaser',
        name: 'Direct Blaser',
        slot: 'secondary',
        modelPath: 'Direct blaser.glb',
        type: 'explosive pistol',
        mechanics: {
            fireMode: 'semi',
            damage: 60,
            headshotMult: 1.0,
            pellets: null,
            fireRate: 60,
            magSize: 4,
            reserveAmmo: 16,
            reloadTime: 2.5,
            reloadType: 'magazine',
            bulletSpeed: 30, // slow projectile
            projectile: true,
            gravity: 9.8,
            splashDamage: 45,
            splashRadius: 5,
            range: Infinity,
            rangeFalloff: null,
            recoilPattern: [[0, 0.3], [0.05, 0.35], [-0.05, 0.35], [0, 0.3], [0.02, 0.32]],
            recoilRecovery: 1.0,
            spread: 0.08,
            adsSpread: 0.04,
            hipfireSpread: null,
            moveSpreadMult: 1.1,
            scopeFOV: null,
            breathSway: null,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: null,
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: null,
        },
        visualFX: {
            muzzleColor: '#FF4400',
            muzzleScale: 3.5,
            tracerColor: '#FF4400',
            tracerWidth: 0.3,
            impactColor: '#FF4400',
            impactScale: 4.0,
            shellEject: true,
        }
    },
    'smg1': {
        id: 'smg1',
        name: 'SMG-1',
        slot: 'secondary',
        modelPath: 'smg1.glb',
        type: 'automatic pistol / machine pistol',
        mechanics: {
            fireMode: 'auto',
            damage: 14,
            headshotMult: 1.3,
            pellets: null,
            fireRate: 1100,
            magSize: 20,
            reserveAmmo: 80,
            reloadTime: 1.4,
            reloadType: 'magazine',
            bulletSpeed: Infinity,
            projectile: false,
            gravity: null,
            splashDamage: null,
            splashRadius: null,
            range: 15,
            rangeFalloff: 0.5,
            recoilPattern: [[0.05, 0.03], [0.08, 0.05], [0.12, 0.08], [0.15, 0.1], [0.1, 0.12], [0.05, 0.15], [0, 0.12], [-0.05, 0.1]],
            recoilRecovery: 2.0,
            spread: 0.09,
            adsSpread: 0.05,
            hipfireSpread: null,
            moveSpreadMult: 1.8,
            scopeFOV: null,
            breathSway: null,
        },
        attachments: {
            rightHand: 'Grip',
            leftHand: null,
        },
        socketMap: {
            rightHand: 'socket_righthand',
            leftHand: null,
        },
        visualFX: {
            muzzleColor: '#44FFFF',
            muzzleScale: 1.5,
            tracerColor: '#44FFFF',
            tracerWidth: 0.06,
            impactColor: '#44FFFF',
            impactScale: 1.0,
            shellEject: true,
        }
    },
};

export default GUN_REGISTRY;
